In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Yil':[2021,2020,2019,2018,2017,2016,2015,2010],
    'Aholi soni':[33.9,33.5,32.9,32.5,31.9,31.4,30.9,28.5],
    'Temp':[1.54,1.48,1.56,1.62,1.65,1.66,1.64,1.53]
}
data

{'Yil': [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
 'Aholi soni': [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
 'Temp': [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53]}

In [5]:
df = pd.DataFrame(data)
df

Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56
3  2018        32.5  1.62
4  2017        31.9  1.65
5  2016        31.4  1.66
6  2015        30.9  1.64
7  2010        28.5  1.53

In [6]:
df = pd.DataFrame(data,columns =['Yil','Temp','Aholi soni'])
df

Yil  Temp  Aholi soni
0  2021  1.54        33.9
1  2020  1.48        33.5
2  2019  1.56        32.9
3  2018  1.62        32.5
4  2017  1.65        31.9
5  2016  1.66        31.4
6  2015  1.64        30.9
7  2010  1.53        28.5

In [7]:
df = pd.DataFrame(data,columns =['Yil','Temp','Aholi soni','YAIM'])
df

Yil  Temp  Aholi soni YAIM
0  2021  1.54        33.9  NaN
1  2020  1.48        33.5  NaN
2  2019  1.56        32.9  NaN
3  2018  1.62        32.5  NaN
4  2017  1.65        31.9  NaN
5  2016  1.66        31.4  NaN
6  2015  1.64        30.9  NaN
7  2010  1.53        28.5  NaN

In [8]:
df = pd.DataFrame(data,columns =['Yil','Temp','Aholi soni','YAIM'],index=[21,20,19,18,17,16,15,10])
df

Yil  Temp  Aholi soni YAIM
21  2021  1.54        33.9  NaN
20  2020  1.48        33.5  NaN
19  2019  1.56        32.9  NaN
18  2018  1.62        32.5  NaN
17  2017  1.65        31.9  NaN
16  2016  1.66        31.4  NaN
15  2015  1.64        30.9  NaN
10  2010  1.53        28.5  NaN

In [10]:
w = pd.Series([1,2,3],index=[21,19,10])
w

21    1
19    2
10    3
dtype: int64

In [11]:
df.YAIM = w

In [12]:
df

Yil  Temp  Aholi soni  YAIM
21  2021  1.54        33.9   1.0
20  2020  1.48        33.5   NaN
19  2019  1.56        32.9   2.0
18  2018  1.62        32.5   NaN
17  2017  1.65        31.9   NaN
16  2016  1.66        31.4   NaN
15  2015  1.64        30.9   NaN
10  2010  1.53        28.5   3.0

In [13]:
type(df.YAIM)

pandas.core.series.Series

In [14]:
val = [1,2,3,4,5,6,7,8]
df.YAIM = val

In [15]:
df

Yil  Temp  Aholi soni  YAIM
21  2021  1.54        33.9     1
20  2020  1.48        33.5     2
19  2019  1.56        32.9     3
18  2018  1.62        32.5     4
17  2017  1.65        31.9     5
16  2016  1.66        31.4     6
15  2015  1.64        30.9     7
10  2010  1.53        28.5     8

In [16]:
df['YAIM'] = val

In [17]:
df[df.YAIM > 3]

Yil  Temp  Aholi soni  YAIM
18  2018  1.62        32.5     4
17  2017  1.65        31.9     5
16  2016  1.66        31.4     6
15  2015  1.64        30.9     7
10  2010  1.53        28.5     8

In [19]:
df.head()

Yil  Temp  Aholi soni  YAIM
21  2021  1.54        33.9     1
20  2020  1.48        33.5     2
19  2019  1.56        32.9     3
18  2018  1.62        32.5     4
17  2017  1.65        31.9     5

In [20]:
df.size

32

In [21]:
df.shape

(8, 4)

In [23]:
df['3+'] = df.YAIM > 3

In [24]:
df

Yil  Temp  Aholi soni  YAIM     3+
21  2021  1.54        33.9     1  False
20  2020  1.48        33.5     2  False
19  2019  1.56        32.9     3  False
18  2018  1.62        32.5     4   True
17  2017  1.65        31.9     5   True
16  2016  1.66        31.4     6   True
15  2015  1.64        30.9     7   True
10  2010  1.53        28.5     8   True

In [1]:
data = {
    'Uzbekistan':{2021:33.9, 2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9},
    'Kazakhstan':{2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8}
}
data

{'Uzbekistan': {2021: 33.9, 2020: 33.5, 2019: 32.9, 2018: 32.5, 2017: 31.9},
 'Kazakhstan': {2021: 18.9,
  2020: 18.7,
  2019: 18.5,
  2018: 18.3,
  2017: 18.1,
  2016: 17.8}}

In [5]:
import pandas as pd

In [6]:
data = {
    'Uzbekistan':{2021:33.9, 2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9},
    'Kazakhstan':{2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8}
}


In [7]:
df = pd.DataFrame(data)

In [8]:
df

Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [9]:
df.values

array([[33.9, 18.9],
       [33.5, 18.7],
       [32.9, 18.5],
       [32.5, 18.3],
       [31.9, 18.1],
       [ nan, 17.8]])

In [10]:
df.index.name = 'Yil'
df

Uzbekistan  Kazakhstan
Yil                         
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [11]:
df2 = pd.DataFrame(data,index=[2020,2018,2016])

In [12]:
df2

Uzbekistan  Kazakhstan
2020        33.5        18.7
2018        32.5        18.3
2016         NaN        17.8

In [13]:
df2.T

2020  2018  2016
Uzbekistan  33.5  32.5   NaN
Kazakhstan  18.7  18.3  17.8

In [15]:
df3 = pd.DataFrame(data,index=[2021,2018])
df3

Uzbekistan  Kazakhstan
2021        33.9        18.9
2018        32.5        18.3

In [16]:
arr = df3.values
arr

array([[33.9, 18.9],
       [32.5, 18.3]])

In [17]:
type(arr)

numpy.ndarray

In [1]:
import pandas as pd
import numpy as np

In [3]:
usernames = {"anvar":"anvarbek223", "olim":"olimtoy", "maryam":"mary334455","javohir":"javohir445"}
emails = {"anvar":"anvar@gmail.com", "olim":"olim@mail.ru", "maryam":"mary33@gmail.com","javohir":"javohir445@gmail.com"}

data = {
    'username':usernames,
    'email':emails
}

df = pd.DataFrame(data)
df

username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com

In [4]:
df.index

Index(['anvar', 'olim', 'maryam', 'javohir'], dtype='object')

In [5]:
arr = ['anvar', 'olim', 'maryam', 'javohir']

In [6]:
arr[0]

'anvar'

In [7]:
arr[1]

'olim'

In [12]:
data2 = {
    'username':{"olim":"olimjon21", "maryam":"maryam2020"},
    'email':{"olim":"olimjon21@mail.ru", "maryam":"maryam20@gmail.com"}
}

data2

{'username': {'olim': 'olimjon21', 'maryam': 'maryam2020'},
 'email': {'olim': 'olimjon21@mail.ru', 'maryam': 'maryam20@gmail.com'}}

In [19]:
df2 = pd.concat([df,pd.DataFrame(data2)],ignore_index=False)
df2

username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
olim       olimjon21     olimjon21@mail.ru
maryam    maryam2020    maryam20@gmail.com

In [20]:
newind = pd.Index(['olim','nafisa','hamida'])
newind

Index(['olim', 'nafisa', 'hamida'], dtype='object')

In [21]:
newind.isin(df2.index)

array([ True, False, False])

In [22]:
df2.index.difference(newind)

Index(['anvar', 'javohir', 'maryam'], dtype='object')

In [23]:
newind.difference(df2.index)

Index(['hamida', 'nafisa'], dtype='object')

In [ ]:
df2.index.union(newind)  # index birlashtirish

Index(['anvar', 'hamida', 'javohir', 'maryam', 'maryam', 'nafisa', 'olim',
       'olim'],
      dtype='object')

In [25]:
df2

username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
olim       olimjon21     olimjon21@mail.ru
maryam    maryam2020    maryam20@gmail.com

In [26]:
df2.index.delete(0)

Index(['olim', 'maryam', 'javohir', 'olim', 'maryam'], dtype='object')

In [27]:
df2

username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
olim       olimjon21     olimjon21@mail.ru
maryam    maryam2020    maryam20@gmail.com

In [28]:
newind.drop('hamida')

Index(['olim', 'nafisa'], dtype='object')

In [29]:
data = {'Yil':[2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
       'Aholi soni':[33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
       'Temp':[1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53],
       'Zichlik':[79.77, 78.68, 77.53, 76.34, 75.13, 73.91, 72.71, 67.03]}

In [31]:
df = pd.DataFrame(data)
df

Yil  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [37]:
data = df['Aholi soni']
data

0    33.9
1    33.5
2    32.9
3    32.5
4    31.9
5    31.4
6    30.9
7    28.5
Name: Aholi soni, dtype: float64

In [34]:
type(data)

pandas.core.series.Series

In [36]:
data = df[['Aholi soni']]
data

Aholi soni
0        33.9
1        33.5
2        32.9
3        32.5
4        31.9
5        31.4
6        30.9
7        28.5

In [38]:
data

0    33.9
1    33.5
2    32.9
3    32.5
4    31.9
5    31.4
6    30.9
7    28.5
Name: Aholi soni, dtype: float64

In [ ]:
data[2]

np.float64(32.9)

In [43]:
type(data)

pandas.core.series.Series

In [45]:
data[2]

np.float64(32.9)

In [47]:
data[0:4]

0    33.9
1    33.5
2    32.9
3    32.5
Name: Aholi soni, dtype: float64

In [48]:
data[[2,3,4]]

2    32.9
3    32.5
4    31.9
Name: Aholi soni, dtype: float64

In [49]:
obj = pd.Series(np.arange(8),index=['a','b','c','d','e','f','g','h'])
obj

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
dtype: int64

In [51]:
obj[['a']]

a    0
dtype: int64

In [52]:
obj['a':'f']

a    0
b    1
c    2
d    3
e    4
f    5
dtype: int64

In [53]:
obj['c':'j']

c    2
d    3
e    4
f    5
g    6
h    7
dtype: int64

In [54]:
obj[[1,5]]

C:\Users\behru\AppData\Local\Temp\ipykernel_3284\619217176.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1,5]]


b    1
f    5
dtype: int64

In [56]:
obj[['a','g']]

a    0
g    6
dtype: int64

In [58]:
obj['a':'c'] = 15
obj

a    15
b    15
c    15
d     3
e     4
f     5
g     6
h     7
dtype: int64

In [63]:
obj[obj < 15]

d    3
e    4
f    5
g    6
h    7
dtype: int64

In [64]:
obj

a    15
b    15
c    15
d     3
e     4
f     5
g     6
h     7
dtype: int64

In [65]:
obj[obj % 2 == 0]

e    4
g    6
dtype: int64